export const DEFAULT_CRAFTS = [
  "Operation Manager",
  "Project Manager",
  "Project Incharge",
  "Project Lead",
  "Site in-charge",
  "Planning Incharge",
  "Planner",
  "QC Incharge",
  "QC Engineer",
  "QC Painting",
  "Civil QA/QC",
  "API inspector",
  "Safety Incharge/ Supervisor",
  "Safety Officer",
  "Sr. Supervisor",
  "Supervisor-Mech",
  "Supervisor-SSD",
  "Supervisor-Catalyst",
  "Supervisor-Fab",
  "Supervisor-HPWJ",
  "Supervisor-Tank",
  "Civil supervisor",
  "Supervisor-Painiting",
  "Supervisor-Blasting",
  "Supervisor-Retubing",
  "Supervisor-Bolting",
  "Supervisor-Instrument",
  "Supervisor-Rigging",
  "Facility Supervisor",
  "Electrical-Engineer",
  "Cost Engineer",
  "Permit Receiver (With ARAMCO Cert.)",
  "Permit Receiver",
  "Trainee Engineer",
  "Foreman-Mech",
  "Foreman-Fab",
  "Foreman-HPWJ",
  "Foreman-Catalyst",
  "Foreman bolting",
  "Foreman-Rigging",
  "Foreman-Tank",
  "Foreman-Store",
  "Foreman-Electrical",
  "HPWJ Jetter / Operator",
  "BA-Technician",
  "Torqueing/tensioning-Technicians",
  "pipe fitter/ Technician",
  "Column Technician",
  "Retubing-Technicians",
  "Catalyst-Technician",
  "Chemical-Technician",
  "Rotary Technician",
  "Millwright Technician",
  "Machinist",
  "Helper/ Labour",
  "Standbyman/ Firewatch",
  "Equipment Watch",
  "ERT crew",
  "Electrician",
  "Mechanic",
  "Time Keeper",
  "Store Keeper",
  "Logistic Co-ordinator",
  "Material Co-ordinator",
  "Project Coordinator",
  "Site Coordinator",
  "Environmental Coordinator",
  "Camp Coordinator",
  "ID Coordinator",
  "Flagman",
  "HD Drivers",
  "LD Drivers",
  "Rigger-I",
  "Rigger-II",
  "Rigger-III",
  "Bundle Puller Operator",
  "Crane Operator",
  "Winch Operator",
  "Forklift Operator",
  "Dry Sucker Operator",
  "Vacuum Truck Operator",
  "BLABO Operator",
  "Decoking Operator",
  "Pigging Operator",
  "Fabricator",
  "Welder (SS & CS)",
  "Firewatch",
  "Gas Cutter",
  "Grinder Man",
  "Sand blaster",
  "Painter",
  "Male Nurse",
  "Autocad",
  "Curran Painter",
  "Curran Technician",
  "Gas Meter Controller",
  "Document Controller",
  "Office",
  "Rigger-I (ARAMCO)",
  "Rigger-II (ARAMCO)",
  "Rigger-III (ARAMCO)",
  "Supervisor Decoking",
  "Foreman SSD",
  "RHD Operator",
  "DPT Crew",
  "Quantity Surveyor",
  "Insulation Tech",
  "Bus Driver",
  "Ambulance Driver",
  "Scaffolder",
  "Jai Durga Engg.",
  "Ramdev",
  "Timekeeper/ Admin Asst.",
  "Security Gate",
  "Camp Helper"
];
